import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Provider from "@/context/client-provider"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Provider>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  )
}
